<a href="https://colab.research.google.com/github/Matig91/Colab-projects/blob/main/CS%20231n%20Convolutional%20NN%20(Stanford)/1.3_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title PLAYGROUND
import numpy as np; import random
np.random.seed(12)
Xte, Xtr = (np.random.randn(7, 9)*10).astype(int), (np.random.randn(5, 9)*10).astype(int) # (30, 9)
yte, ytr = ((np.random.randn(Xte.shape[0])*20) % 3).astype(int), ((np.random.randn(Xtr.shape[0])*20) % 3).astype(int)
Nte, Ntr = Xte.shape[0], Xtr.shape[0]

# generate a random SVM weight matrix of small numbers
W = np.random.randn(Xtr.shape[1], np.max(ytr)+1) * 0.01

# Xte, W
ytr, Xtr, W, Nte, Ntr

(array([2, 2, 1, 1, 1]),
 array([[  6,   5,   2, -15,  10, -11, -10,  -1,   5],
        [ 14, -16,  14,  16,  -4,  -2,  -5,  -6, -13],
        [-16,  -1,   2,  18, -10, -20,   1,  -4,   3],
        [ -3, -12,  -6,   8,   2,  -9,   8, -14,  -5],
        [  1, -13, -11,   0,   0,  -2,  -5, -11,  -7]]),
 array([[ 0.01522842,  0.01461882,  0.00037656],
        [-0.00246197, -0.00664298,  0.00351336],
        [-0.00484031, -0.01513087, -0.0076353 ],
        [ 0.00249203, -0.01589809, -0.00979526],
        [ 0.00122762,  0.01689292,  0.0017775 ],
        [ 0.00032006,  0.01933216, -0.01062095],
        [-0.00732629,  0.00842741,  0.0107674 ],
        [ 0.00457691, -0.02619493,  0.00739046],
        [ 0.00667501,  0.00046403,  0.00666078]]),
 7,
 5)

In [ ]:
# Initialize the loss and gradient to zero
reg = 0.1; loss = 0.0; dW = np.zeros_like(W)
num_classes = W.shape[1]

scores = Xtr.dot(W);print(scores)

for i in range(Ntr):
  scr_nm = scores[i] - np.max(scores[i]) # num stability
  softmax = np.exp(scr_nm)/np.sum(np.exp(scr_nm))

  # print(f"({scr_nm.shape}, {np.round(scr_nm, 1)}, {np.round(softmax, 2)}, {ytr[i]})") if i < 2 else "Pass"

  loss      += -np.log(softmax[ytr[i]])

  # Weight Gradients
  for j in range(num_classes):
    dW[:,j]   += Xtr[i] * softmax[j]
    print(f"{dW[:,j].round(2)}", softmax[j])
  dW[:,ytr[i]] -= Xtr[i]; print(f"{dW[:, ytr[i]:].round(2)}, {dW.round(2)}")

loss /= Ntr;  dW  /= Ntr; print(loss)        # Average

loss += reg * np.sum(W*W)       # Reg-n
dW   += 2 * reg * np.sum(W)
# loss, dW

[[ 0.14281609  0.16322404  0.20432924]
 [ 0.14154181 -0.15248625 -0.48519823]
 [-0.23030301 -0.9846586  -0.00529176]
 [-0.12365081  0.29108447 -0.02732784]
 [ 0.03939781  0.47151181 -0.12182434]]
[ 1.95  1.62  0.65 -4.86  3.24 -3.57 -3.24 -0.32  1.62] 0.324247688232743
[ 1.99  1.65  0.66 -4.96  3.31 -3.64 -3.31 -0.33  1.65] 0.330932900076509
[ 2.07  1.72  0.69 -5.17  3.45 -3.79 -3.45 -0.34  1.72] 0.34481941169074803
[[-3.93]
 [-3.28]
 [-1.31]
 [ 9.83]
 [-6.55]
 [ 7.21]
 [ 6.55]
 [ 0.66]
 [-3.28]], [[ 1.95  1.99 -3.93]
 [ 1.62  1.65 -3.28]
 [ 0.65  0.66 -1.31]
 [-4.86 -4.96  9.83]
 [ 3.24  3.31 -6.55]
 [-3.57 -3.64  7.21]
 [-3.24 -3.31  6.55]
 [-0.32 -0.33  0.66]
 [ 1.62  1.65 -3.28]]
[ 8.09 -5.4   6.79  2.16  1.49 -4.44 -5.44 -2.96 -4.08] 0.43867606136871695
[ 6.56 -3.58  5.24  0.27  2.   -4.29 -4.94 -2.29 -2.6 ] 0.3269257820106698
[-0.65 -7.03  1.97 13.58 -7.49  6.74  5.38 -0.75 -6.32] 0.23439815662061336
[[-14.65]
 [  8.97]
 [-12.03]
 [ -2.42]
 [ -3.49]
 [  8.74]
 [ 10.38]
 [  5.25]


In [ ]:
# Initialize the loss and gradient to zero
reg = 0.1; loss = 0.0; dW = np.zeros_like(W)
num_classes = W.shape[1]

scores = Xtr.dot(W); print(scores)

num_classes = W.shape[1]
num_train   = Xtr.shape[0]
scores = scores - np.max(scores, axis=1, keepdims=True)                          # num stability
softmax = np.exp(scores)/np.sum(np.exp(scores), axis=1, keepdims=True)

loss = -np.sum(np.log(softmax[np.arange(Ntr),ytr]), keepdims=True)

dW           =  np.matmul(Xtr.T, softmax)             # dim x class = X.T(dim x num) | num x class
yenc = np.zeros((Ntr, num_classes))
yenc[np.arange(Ntr), ytr] = 1
dW          -= Xtr.T @ yenc   # dim x class = dim x num | num x class = X.T @ (num x 1)

# loss += reg * np.sum(W*W)       # Reg-n
# dW   += 2 * reg * np.sum(W)
# loss /= Ntr;  dW  /= Ntr
loss, dW

[[ 0.14281609  0.16322404  0.20432924]
 [ 0.14154181 -0.15248625 -0.48519823]
 [-0.23030301 -0.9846586  -0.00529176]
 [-0.12365081  0.29108447 -0.02732784]
 [ 0.03939781  0.47151181 -0.12182434]]


(array([5.93100173]),
 array([[  1.67531309,  20.99653551, -22.67184859],
        [-12.91727585,  11.32084972,   1.59642613],
        [  2.62153245,  13.07522555, -15.696758  ],
        [ 10.97925631, -19.27350228,   8.29424597],
        [ -1.63188164,   9.11179979,  -7.47991815],
        [-14.86911819,  18.5735098 ,  -3.70439162],
        [ -4.3298429 ,  -7.69193632,  12.02177922],
        [-11.54141647,  15.15712555,  -3.61570907],
        [ -6.42669067,   1.64940853,   4.77728214]]))

In [ ]:
# This mounts your Google Drive to the Colab VM.
from google.colab import drive
drive.mount('/content/drive')

# TODO: Enter the foldername in your Drive where you have saved the unzipped
# assignment folder, e.g. 'cs231n/assignments/assignment1/'

FOLDERNAME = 'cs231n/assignments/assignment1/'
assert FOLDERNAME is not None, "[!] Enter the foldername."

# Now that we've mounted your Drive, this ensures that
# the Python interpreter of the Colab VM can load
# python files from within it

import sys
sys.path.append('/content/drive/My Drive/{}'.format(FOLDERNAME))

# This downloads the CIFAR-10 dataset to your Drive
# if it doesn't already exist.
%cd /content/drive/My\ Drive/$FOLDERNAME/cs231n/datasets/
!bash get_datasets.sh
%cd /content/drive/My\ Drive/$FOLDERNAME

Mounted at /content/drive
/content/drive/My Drive/cs231n/assignments/assignment1/cs231n/datasets
/content/drive/My Drive/cs231n/assignments/assignment1


# Softmax exercise

*Complete and hand in this completed worksheet (including its outputs and any supporting code outside of the worksheet) with your assignment submission. For more details see the [assignments page](http://vision.stanford.edu/teaching/cs231n/assignments.html) on the course website.*

This exercise is analogous to the SVM exercise. You will:

- implement a fully-vectorized **loss function**
for the Softmax classifier
- implement the fully-vectorized expression
for its **analytic gradient**
- **check your implementation**
with numerical gradient
- use a validation set to
**tune the learning rate and
regularization** strength
- **optimize**
the loss function
with **SGD**
- **visualize** the final learned weights


In [ ]:
import random
import numpy as np
from cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [ ]:
def get_CIFAR10_data(num_training=49000, num_validation=1000, num_test=1000, num_dev=500):
    """    Load the CIFAR-10 dataset from disk and perform preprocessing to prepare
    it for the linear classifier. These are the same steps as we used for the
    SVM, but condensed to a single function. """

    # Load the raw CIFAR-10 data
    cifar10_dir = 'cs231n/datasets/cifar-10-batches-py'

    # Cleaning up variables to prevent loading data multiple times (which may cause memory issue)
    try:
       del X_train, y_train
       del X_test, y_test
       print('Clear previously loaded data.')
    except:
       pass

    X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

    # subsample the data
    mask = list(range(num_training, num_training + num_validation))
    X_val = X_train[mask]
    y_val = y_train[mask]
    mask = list(range(num_training))
    X_train = X_train[mask]
    y_train = y_train[mask]
    mask = list(range(num_test))
    X_test = X_test[mask]
    y_test = y_test[mask]
    mask = np.random.choice(num_training, num_dev, replace=False)
    X_dev = X_train[mask]
    y_dev = y_train[mask]

    # Preprocessing: reshape the image data into rows
    X_train = np.reshape(X_train, (X_train.shape[0], -1))
    X_val = np.reshape(X_val, (X_val.shape[0], -1))
    X_test = np.reshape(X_test, (X_test.shape[0], -1))
    X_dev = np.reshape(X_dev, (X_dev.shape[0], -1))

    # Normalize the data: subtract the mean image
    mean_image = np.mean(X_train, axis = 0)
    X_train -= mean_image
    X_val -= mean_image
    X_test -= mean_image
    X_dev -= mean_image

    # add bias dimension and transform into columns
    X_train = np.hstack([X_train, np.ones((X_train.shape[0], 1))])
    X_val = np.hstack([X_val, np.ones((X_val.shape[0], 1))])
    X_test = np.hstack([X_test, np.ones((X_test.shape[0], 1))])
    X_dev = np.hstack([X_dev, np.ones((X_dev.shape[0], 1))])

    return X_train, y_train, X_val, y_val, X_test, y_test, X_dev, y_dev


# Invoke the above function to get our data.
X_train, y_train, X_val, y_val, X_test, y_test, X_dev, y_dev = get_CIFAR10_data()
print('Train data shape: ', X_train.shape)
print('Train labels shape: ', y_train.shape)
print('Validation data shape: ', X_val.shape)
print('Validation labels shape: ', y_val.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)
print('dev data shape: ', X_dev.shape)
print('dev labels shape: ', y_dev.shape)

Train data shape:  (49000, 3073)
Train labels shape:  (49000,)
Validation data shape:  (1000, 3073)
Validation labels shape:  (1000,)
Test data shape:  (1000, 3073)
Test labels shape:  (1000,)
dev data shape:  (500, 3073)
dev labels shape:  (500,)


## Softmax Classifier

Your code for this section will all be written inside `cs231n/classifiers/softmax.py`.


In [ ]:
from builtins import range
import numpy as np
from random import shuffle
from past.builtins import xrange

def softmax_loss_naive(W, X, y, reg):
    """   Softmax loss function, naive implementation (with loops)
    Inputs have dimension D, there are C classes, and we operate on minibatches of N examples.
    Inputs:  - W: A numpy array of shape (D, C) containing weights.
    - X: A numpy array of shape (N, D) containing a minibatch of data.
    - y: A numpy array of shape (N,) containing aining labels; y[i] = c means
      that X[i] has label c, where 0 <= c < C.  - reg: (float) regularization strength
    Returns a tuple of:  - loss as single float
    - gradient with respect to weights W; an array of same shape as W           """
    # Initialize the loss and gradient to zero
    loss = 0.0; dW = np.zeros_like(W)
    """ # TODO: Compute the softmax loss and its gradient using explicit loops
    # Store the loss in loss and the gradient in dW. If you are not careful     #
    # here, it is easy to run into numeric instability. Don't forget the        #
    # regularization!       """

    scores = X.dot(W)
    num_classes = W.shape[1]
    num_train   = X.shape[0]
    for i in range(num_train):
      f = scores[i] - np.max(scores[i]) # num stability
      softmax = np.exp(f)/np.sum(np.exp(f))
      # print(f.shape)
      loss     += -np.log(softmax[y[i]])
      for j in range(num_classes):

        dW[:,j]  += X[i] * softmax[j]
      dW[:,y[i]] -= X[i]

    # Average
    loss /= num_train;  dW   /= num_train
    # Reg-n
    loss += reg * np.sum(W*W)
    dW   += 2 * reg * W

    return loss, dW

def softmax_loss_vectorized(W, X, y, reg):
    """ Softmax loss function, vectorized version.
    Inputs and outputs are the same as softmax_loss_naive. """
    # Initialize the loss and gradient to zero

    loss = 0.0
    dW = np.zeros_like(W)
    """  # TODO: Compute the softmax loss and its gradient using no explicit loops.
    Store the loss in loss and the gradient in dW. If you are not careful
    here, it is easy to run into numeric instability. Don't forget the regularization!  """

    scores      = X.dot(W)
    num_classes = W.shape[1]
    num_train   = X.shape[0]

    scores = scores - np.max(scores, axis=1, keepdims=True)                          # num stability
    softmax = np.exp(scores)/np.sum(np.exp(scores), axis=1, keepdims=True)

    loss = -np.sum(np.log(softmax[np.arange(num_train),y]), keepdims=True)

    dW           =  np.matmul(X.T, softmax)             # dim x class = X.T(dim x num) | num x class
    yenc         = np.zeros((num_train, num_classes))
    yenc[np.arange(num_train), y] = 1
    dW          -= X.T @ yenc   # dim x class = dim x num | num x class = X.T @ (num x 1)
    # Average
    loss /= num_train;  dW   /= num_train

    # Reg-n
    loss += reg * np.sum(W*W)
    dW   += 2 * reg * W

    return loss, dW

def softmax_loss_vectorized_2(W, X, y, reg):
    loss = 0.0;    dW = np.zeros_like(W)

    scores = X.dot(W)

    num_classes = W.shape[1]
    num_train   = X.shape[0]
    scores = scores - np.max(scores, axis=1, keepdims=True)                          # num stability

    softmax = np.exp(scores)/np.sum(np.exp(scores), axis=1, keepdims=True)
    loss = -np.sum(np.log(softmax[np.arange(num_train),y]), keepdims=True)
    softmax[np.arange(num_train), y] += -1              # Softmax Matrix
    dW           =  np.matmul(X.T, softmax)             # dim x class = X.T(dim x num) | num x class

    loss /= num_train;  dW   /= num_train
    loss += reg * np.sum(W*W);    dW   += 2 * reg * W
    return loss, dW

In [ ]:
# First implement the naive softmax loss function with nested loops.
# Open the file cs231n/classifiers/softmax.py and implement the softmax_loss_naive function.

# from cs231n.classifiers.softmax import softmax_loss_naive
import time

# Generate a random softmax weight matrix and use it to compute the loss.
W = np.random.randn(3073, 10) * 0.0001
loss, grad = softmax_loss_naive(W, X_dev, y_dev, 0.0)

# As a rough sanity check, our loss should be something close to -log(0.1)

print('loss: %f' % loss)
print('sanity check: %f' % (-np.log(0.1)))

loss: 2.377234
sanity check: 2.302585


**Inline Question 1**

Why do we expect our loss to be close to -log(0.1)? Explain briefly.**

$\color{blue}{\textit Your Answer:}$ *Fill this in*



In [ ]:
# Complete the implementation of softmax_loss_naive and implement a (naive)
# version of the gradient that uses nested loops.
loss, grad = softmax_loss_naive(W, X_dev, y_dev, 0.0)

# As we did for the SVM, use numeric gradient checking as a debugging tool.
# The numeric gradient should be close to the analytic gradient.
from cs231n.gradient_check import grad_check_sparse
f = lambda w: softmax_loss_naive(w, X_dev, y_dev, 0.0)[0]
grad_numerical = grad_check_sparse(f, W, grad, 10)

# similar to SVM case, do another gradient check with regularization
loss, grad = softmax_loss_naive(W, X_dev, y_dev, 5e1)
f = lambda w: softmax_loss_naive(w, X_dev, y_dev, 5e1)[0]
grad_numerical = grad_check_sparse(f, W, grad, 10)

numerical: 1.054027 analytic: 1.054027, relative error: 3.282981e-08
numerical: 0.993024 analytic: 0.993024, relative error: 2.612990e-08
numerical: -1.208416 analytic: -1.208416, relative error: 1.776983e-08
numerical: 1.982605 analytic: 1.982605, relative error: 3.193292e-08
numerical: 0.195423 analytic: 0.195423, relative error: 1.256295e-07
numerical: 1.481976 analytic: 1.481976, relative error: 3.063556e-09
numerical: -0.679049 analytic: -0.679049, relative error: 1.049748e-08
numerical: -1.129731 analytic: -1.129731, relative error: 3.619672e-08
numerical: 1.673342 analytic: 1.673342, relative error: 9.985797e-09
numerical: 3.016227 analytic: 3.016227, relative error: 2.452829e-08
numerical: -0.845418 analytic: -0.845418, relative error: 6.688012e-08
numerical: 0.244975 analytic: 0.244975, relative error: 7.784579e-08
numerical: -1.744015 analytic: -1.744015, relative error: 4.107161e-08
numerical: 2.019824 analytic: 2.019824, relative error: 5.540835e-09
numerical: 0.167891 anal

In [ ]:
# Now that we have a naive implementation of the softmax loss function and its gradient,
# implement a vectorized version in softmax_loss_vectorized.
# The two versions should compute the same results, but the vectorized version should be
# much faster.
tic = time.time()
loss_naive, grad_naive = softmax_loss_naive(W, X_dev, y_dev, 0.000005)
toc = time.time()
print('naive loss: %e computed in %fs' % (loss_naive, toc - tic))

# from cs231n.classifiers.softmax import softmax_loss_vectorized
tic = time.time()
loss_vectorized, grad_vectorized = softmax_loss_vectorized(W, X_dev, y_dev, 0.000005)
toc = time.time()
print('vectorized loss: %e computed in %fs' % (loss_vectorized, toc - tic))

# As we did for the SVM, we use the Frobenius norm to compare the two versions
# of the gradient.
grad_difference = np.linalg.norm(grad_naive - grad_vectorized, ord='fro')
print('Loss difference: %f' % np.abs(loss_naive - loss_vectorized))
print('Gradient difference: %f' % grad_difference)

naive loss: 2.377234e+00 computed in 0.079351s
vectorized loss: 2.377234e+00 computed in 0.016420s
Loss difference: 0.000000
Gradient difference: 0.000000


<ipython-input-10-f186fa079dd8>:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('vectorized loss: %e computed in %fs' % (loss_vectorized, toc - tic))
<ipython-input-10-f186fa079dd8>:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('Loss difference: %f' % np.abs(loss_naive - loss_vectorized))


In [ ]:
""" Use the validation set to tune hyperparameters (regularization strength and
learning rate). You should experiment with different ranges for the learning
rates and regularization strengths; if you are careful you should be able to
get a classification accuracy of over 0.35 on the validation set."""
# from cs231n.classifiers import Softmax
import itertools
results = {};  best_val = -1;  best_softmax = None;  num_iters = 500
batch_size=128; num_train = X_train.shape[0]
loss_history = []

# X_batch = np.zeros((batch_size, X_train.shape[1]))
# y_batch = np.zeros(batch_size)
"""TODO: Use the validation set to set the learning rate and regularization strength. #
This should be identical to the validation that you did for the SVM; save the best trained softmax classifer in best_softmax."""

# Provided as a reference. You may or may not want to change these hyperparameters
learning_rates = [0.5e-5, 2e-6] #, 2.5e-6]
regularization_strengths = [1e2, 1e4] #, 2e4, 2.5e4, 3e4, 3.5e4]
y_predv, y_predt = np.zeros_like(y_val), np.zeros_like(y_train)

for lr, reg in zip(learning_rates[:1], regularization_strengths[:1]): # itertools.product(learning_rates, regularization_strengths):
  W = np.random.randn(3073, 10) * 0.0001
  for i in range(num_iters):
    batch_indices = np.random.choice(num_train, batch_size, replace=False)
    X_batch = X_train[batch_indices]
    y_batch = y_train[batch_indices]
    loss_vectorized, dW = softmax_loss_vectorized_2(W, X_batch, y_batch, reg)
    W = W - lr * dW # W -= lr * dW
    # loss_history.append(loss_vectorized)
    loss_history.append(loss_vectorized) if i % 100 == 0 else None

  scores_val = X_val.dot(W)
  y_predv = np.argmax(scores_val, axis=1, keepdims=True)
  val_accuracy = np.mean(y_predv == y_val)

  scores_train = X_train.dot(W)
  y_predt = np.argmax(scores_train, axis=1, keepdims=True)
  train_accuracy = np.mean(y_predt == y_train)

  results[(lr, reg)] = (train_accuracy, val_accuracy)

  if val_accuracy > best_val:
    best_val = val_accuracy
    # best_softmax[(lr, reg)] = W

# Print out results.
for lr, reg in sorted(results):
    train_accuracy, val_accuracy = results[(lr, reg)]
    print('lr %e reg %e train accuracy: %f val accuracy: %f' % (
                lr, reg, train_accuracy, val_accuracy))

print('best validation accuracy achieved during cross-validation: %f' % best_val)
loss_history

lr 5.000000e-06 reg 1.000000e+02 train accuracy: 0.100021 val accuracy: 0.099424
best validation accuracy achieved during cross-validation: 0.099424


[array([2.43291893]),
 array([1.93933504]),
 array([1.74684112]),
 array([1.83098942]),
 array([1.78769109]),
 array([1.97127265]),
 array([1.94060429]),
 array([1.77554717]),
 array([1.82535782]),
 array([1.6630771]),
 array([1.92452468]),
 array([1.88186939]),
 array([2.08367871]),
 array([1.78001541]),
 array([1.83243303]),
 array([1.78951735]),
 array([1.78578811]),
 array([1.8034427]),
 array([1.96068822]),
 array([1.77060271]),
 array([1.99553176]),
 array([1.91564778]),
 array([1.71903142]),
 array([1.97616412]),
 array([1.89377947]),
 array([1.69175143]),
 array([1.98372339]),
 array([1.77603423]),
 array([1.74337892]),
 array([1.80547001]),
 array([1.63293021]),
 array([1.91412656]),
 array([1.87853023]),
 array([1.67292044]),
 array([1.90602562]),
 array([1.86382669]),
 array([2.06641869]),
 array([2.12823704]),
 array([1.94773029]),
 array([2.05780777]),
 array([1.92151033]),
 array([1.82866483]),
 array([1.91320803]),
 array([1.79772494]),
 array([1.59535556]),
 array([2.04

In [ ]:
# evaluate on test set
# Evaluate the best softmax on test set
y_test_pred = best_softmax.predict(X_test)
test_accuracy = np.mean(y_test == y_test_pred)
print('softmax on raw pixels final test set accuracy: %f' % (test_accuracy, ))

**Inline Question 2** - *True or False*

Suppose the overall training loss is defined as the sum of the per-datapoint loss over all training examples. It is possible to add a new datapoint to a training set that would leave the SVM loss unchanged, but this is not the case with the Softmax classifier loss.

$\color{blue}{\textit Your Answer:}$


$\color{blue}{\textit Your Explanation:}$



In [ ]:
# Visualize the learned weights for each class
w = best_softmax.W[:-1,:] # strip out the bias
w = w.reshape(32, 32, 3, 10)

w_min, w_max = np.min(w), np.max(w)

classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
for i in range(10):
    plt.subplot(2, 5, i + 1)

    # Rescale the weights to be between 0 and 255
    wimg = 255.0 * (w[:, :, :, i].squeeze() - w_min) / (w_max - w_min)
    plt.imshow(wimg.astype('uint8'))
    plt.axis('off')
    plt.title(classes[i])